export type Deal = {
  id: number;
  categorySlug: string;
  categoryName: string;
  subcategory: string;
  title: string;
  subtitle: string;
  image: string;
  originalPrice: number;
  currentPrice: number;
  lowestPrice: number;
  participants: number;
  targetParticipants: number;
  endsIn: string;
  badge: string;
  deliveryBadge: string;
  seller: string;
  rating: number;
  reviewCount: number;
  tags: string[];
};

export const deals: Deal[] = [
  {
    id: 1,
    categorySlug: "fresh-food",
    categoryName: "식품",
    subcategory: "과일",
    title: "제주 감귤 3kg 산지직송",
    subtitle: "오늘 수확, 내일 도착",
    image: "🍊",
    originalPrice: 22900,
    currentPrice: 14900,
    lowestPrice: 12900,
    participants: 86,
    targetParticipants: 120,
    endsIn: "02:18:44",
    badge: "실시간 인기",
    deliveryBadge: "내일도착",
    seller: "제주하루농장",
    rating: 4.8,
    reviewCount: 1284,
    tags: ["산지직송", "무료배송", "신선보장"],
  },
  {
    id: 2,
    categorySlug: "fresh-food",
    categoryName: "식품",
    subcategory: "정육",
    title: "프리미엄 한우 불고기 600g",
    subtitle: "냉장 배송 특가",
    image: "🥩",
    originalPrice: 39800,
    currentPrice: 27900,
    lowestPrice: 24900,
    participants: 51,
    targetParticipants: 80,
    endsIn: "04:52:11",
    badge: "최저가 임박",
    deliveryBadge: "콜드체인",
    seller: "바른한우",
    rating: 4.7,
    reviewCount: 842,
    tags: ["냉장배송", "당일손질", "명절선물"],
  },
  {
    id: 3,
    categorySlug: "household",
    categoryName: "생활용품",
    subcategory: "물티슈",
    title: "국내산 대용량 물티슈 20팩",
    subtitle: "육아 필수템 공동구매",
    image: "🧻",
    originalPrice: 31900,
    currentPrice: 19900,
    lowestPrice: 17900,
    participants: 142,
    targetParticipants: 200,
    endsIn: "07:05:29",
    badge: "생활특가",
    deliveryBadge: "무료배송",
    seller: "데일리케어",
    rating: 4.9,
    reviewCount: 3210,
    tags: ["대용량", "무향", "캡형"],
  },
  {
    id: 4,
    categorySlug: "fresh-food",
    categoryName: "식품",
    subcategory: "커피/음료",
    title: "성수동 디카페인 콜드브루 12병",
    subtitle: "카페 납품 원두 사용",
    image: "☕",
    originalPrice: 36000,
    currentPrice: 23900,
    lowestPrice: 21900,
    participants: 68,
    targetParticipants: 100,
    endsIn: "11:41:02",
    badge: "신규 오픈",
    deliveryBadge: "새벽출고",
    seller: "성수브루어리",
    rating: 4.6,
    reviewCount: 536,
    tags: ["디카페인", "무설탕", "홈카페"],
  },
  {
    id: 5,
    categorySlug: "beauty",
    categoryName: "뷰티",
    subcategory: "마스크팩",
    title: "진정 수분 마스크팩 30매 세트",
    subtitle: "민감 피부용 데일리 케어",
    image: "🧖",
    originalPrice: 42000,
    currentPrice: 23900,
    lowestPrice: 19900,
    participants: 214,
    targetParticipants: 300,
    endsIn: "05:30:18",
    badge: "뷰티랭킹",
    deliveryBadge: "무료배송",
    seller: "블룸스킨",
    rating: 4.8,
    reviewCount: 1890,
    tags: ["저자극", "수분진정", "1일1팩"],
  },
  {
    id: 6,
    categorySlug: "baby",
    categoryName: "출산/육아",
    subcategory: "기저귀",
    title: "프리미엄 밴드 기저귀 4팩",
    subtitle: "샘 방지 흡수층 업그레이드",
    image: "👶",
    originalPrice: 76000,
    currentPrice: 54900,
    lowestPrice: 49900,
    participants: 93,
    targetParticipants: 150,
    endsIn: "09:16:03",
    badge: "육아추천",
    deliveryBadge: "무료배송",
    seller: "베베라운지",
    rating: 4.7,
    reviewCount: 2476,
    tags: ["대용량", "밤기저귀", "정기구매"],
  },
  {
    id: 7,
    categorySlug: "digital",
    categoryName: "가전/디지털",
    subcategory: "이어폰",
    title: "노이즈캔슬링 무선 이어폰",
    subtitle: "출퇴근 필수 가성비 오디오",
    image: "🎧",
    originalPrice: 129000,
    currentPrice: 79900,
    lowestPrice: 69900,
    participants: 119,
    targetParticipants: 180,
    endsIn: "13:42:58",
    badge: "디지털핫딜",
    deliveryBadge: "오늘출발",
    seller: "테크와이드",
    rating: 4.5,
    reviewCount: 713,
    tags: ["ANC", "저지연", "케이스포함"],
  },
  {
    id: 8,
    categorySlug: "home-living",
    categoryName: "홈/인테리어",
    subcategory: "침구",
    title: "호텔식 사계절 차렵이불 세트",
    subtitle: "먼지 적은 부드러운 침구",
    image: "🛏️",
    originalPrice: 89000,
    currentPrice: 57900,
    lowestPrice: 52900,
    participants: 77,
    targetParticipants: 120,
    endsIn: "01:58:25",
    badge: "마감임박",
    deliveryBadge: "무료배송",
    seller: "코지홈",
    rating: 4.6,
    reviewCount: 1027,
    tags: ["알러지케어", "먼지적음", "세트구성"],
  },
  {
    id: 9,
    categorySlug: "pet",
    categoryName: "반려동물",
    subcategory: "고양이사료",
    title: "고단백 고양이 사료 6kg",
    subtitle: "기호성 높은 전연령 레시피",
    image: "🐱",
    originalPrice: 68000,
    currentPrice: 45900,
    lowestPrice: 41900,
    participants: 64,
    targetParticipants: 100,
    endsIn: "16:08:40",
    badge: "펫특가",
    deliveryBadge: "무료배송",
    seller: "펫테이블",
    rating: 4.7,
    reviewCount: 654,
    tags: ["고단백", "전연령", "대용량"],
  },
  {
    id: 10,
    categorySlug: "kitchen",
    categoryName: "주방용품",
    subcategory: "프라이팬",
    title: "논스틱 프라이팬 3종 세트",
    subtitle: "인덕션 겸용 주방 베스트",
    image: "🍳",
    originalPrice: 59000,
    currentPrice: 36900,
    lowestPrice: 32900,
    participants: 132,
    targetParticipants: 180,
    endsIn: "06:24:12",
    badge: "주방베스트",
    deliveryBadge: "무료배송",
    seller: "키친메이트",
    rating: 4.8,
    reviewCount: 1192,
    tags: ["인덕션", "3종세트", "PFOA-free"],
  },
];
