import Link from "next/link";
import { notFound } from "next/navigation";

import { markOrderPreparingAction, saveSellerInvoiceAction, saveSellerOrderMemoAction } from "@/app/actions/seller/actions";
import { BottomNavigation } from "@/components/bottom-navigation";
import { Header } from "@/components/header";
import { getSellerOrder, sellerOrders } from "@/lib/seller";
import { formatWon } from "@/lib/format";

type Props = { params: Promise<{ id: string }> };
export function generateStaticParams(){ return sellerOrders.map((order)=>({ id: order.id })); }
export default async function SellerOrderDetailPage({ params }: Props){
  const { id } = await params;
  const order = getSellerOrder(id);
  if(!order) notFound();
  return <main className="mx-auto min-h-screen max-w-[480px] bg-white pb-24 shadow-soft"><Header /><div className="space-y-4 px-4 pt-4 pb-8"><section className="rounded-2xl bg-wadeal-ink p-5 text-white"><p className="text-xs font-black text-red-200">Order Detail</p><h1 className="mt-2 text-2xl font-black">주문 상세</h1><p className="mt-2 text-sm font-bold text-gray-200">{order.id} · {order.status}</p></section><section className="rounded-2xl border border-wadeal-line bg-white p-4"><h2 className="text-base font-black text-wadeal-ink">{order.product}</h2><dl className="mt-3 grid grid-cols-2 gap-2 text-xs font-bold"><div className="rounded-xl bg-gray-50 p-3"><dt className="text-wadeal-muted">구매자</dt><dd className="mt-1 text-wadeal-ink">{order.buyer}</dd></div><div className="rounded-xl bg-gray-50 p-3"><dt className="text-wadeal-muted">수량</dt><dd className="mt-1 text-wadeal-ink">{order.quantity}</dd></div><div className="rounded-xl bg-gray-50 p-3"><dt className="text-wadeal-muted">결제금액</dt><dd className="mt-1 text-wadeal-red">{formatWon(order.amount)}</dd></div><div className="rounded-xl bg-gray-50 p-3"><dt className="text-wadeal-muted">송장</dt><dd className="mt-1 text-wadeal-ink">{order.invoice ?? '미입력'}</dd></div></dl></section><form action={markOrderPreparingAction} className="rounded-2xl border border-wadeal-line bg-white p-4"><input name="orderId" type="hidden" value={order.id} /><h2 className="text-base font-black text-wadeal-ink">배송 준비중 처리</h2><p className="mt-2 text-xs font-bold text-wadeal-muted">신규 주문을 확인하고 배송 준비 상태로 변경합니다.</p><button className="mt-3 h-10 w-full rounded-xl bg-wadeal-red text-xs font-black text-white" type="submit">배송 준비중으로 변경</button></form><form action={saveSellerInvoiceAction} className="rounded-2xl border border-wadeal-line bg-white p-4"><input name="orderId" type="hidden" value={order.id} /><h2 className="text-base font-black text-wadeal-ink">송장번호 입력</h2><input className="mt-3 h-10 w-full rounded-xl bg-gray-50 px-3 text-sm font-bold outline-none" name="invoice" defaultValue={order.invoice ?? ''} placeholder="송장번호" /><button className="mt-3 h-10 w-full rounded-xl bg-wadeal-red text-xs font-black text-white" type="submit">송장 저장</button></form><form action={saveSellerOrderMemoAction} className="rounded-2xl border border-wadeal-line bg-white p-4"><input name="orderId" type="hidden" value={order.id} /><h2 className="text-base font-black text-wadeal-ink">주문 메모</h2><textarea className="mt-3 min-h-24 w-full rounded-xl bg-gray-50 p-3 text-sm font-bold outline-none" name="memo" defaultValue={order.memo ?? ''} /><button className="mt-3 h-10 w-full rounded-xl border border-wadeal-line text-xs font-black text-wadeal-ink" type="submit">메모 저장</button></form><Link className="block text-center text-sm font-black text-wadeal-red" href="/seller/orders">목록으로</Link></div><BottomNavigation /></main>;
}
